-- File: src/main/resources/db/migration/V1__create_initial_tables.sql

-- Tabela para os Cursos
CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL UNIQUE,
    category_course VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

-- Tabela para os Professores
CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    specialty VARCHAR(100) NOT NULL,
    stack VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

-- Tabela para os Alunos
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Tabela para os Tópicos (com chaves estrangeiras para Aluno e Curso)
CREATE TABLE topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    creation_date TIMESTAMP NOT NULL,
    status VARCHAR(100) NOT NULL,
    author_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (author_id) REFERENCES students(id),
    FOREIGN KEY (course_id) REFERENCES courses(id)
);

-- Tabela de Junção para Matrículas (Alunos <-> Cursos)
CREATE TABLE enrollments (
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    PRIMARY KEY (student_id, course_id),
    FOREIGN KEY (student_id) REFERENCES students(id),
    FOREIGN KEY (course_id) REFERENCES courses(id)
);

-- Tabela de Junção para Associação de Professores (Cursos <-> Professores)
CREATE TABLE course_teacher_assignments (
    course_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    PRIMARY KEY (course_id, teacher_id),
    FOREIGN KEY (course_id) REFERENCES courses(id),
    FOREIGN KEY (teacher_id) REFERENCES teachers(id)
);
